---
# Source: erpnext/templates/job-backup.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: erpnext-backup-20240825235347
  labels:
    helm.sh/chart: erpnext-7.0.107
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/version: "v15.33.5"
    app.kubernetes.io/managed-by: Helm
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      containers:
      - name: backup
        image: "ghcr.io/finkash-pty/frappe/erpnext:v15"
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          - >
            bench --site=$(SITE_NAME)
            backup --with-files;
        env:
          - name: "SITE_NAME"
            value: "skm.finkash.co.za"
        resources:
          {}
        securityContext:
          capabilities:
            add:
            - CAP_CHOWN
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
        - name: logs
          emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64
